In [9]:
from model import Autoencoder, CustomTransformerModel, EncocderWrapper
from data_loader import MNISTRandomSampler
import torch
import torch.nn as nn
import torch.optim as optim

In [10]:
autoencoder_path = "autoencoder_mnist.pth"
latent_dim = 15
device = "mps"

In [11]:
autoencoder = Autoencoder(latent_dim).to(device)
autoencoder.load_state_dict(torch.load(autoencoder_path))
autoencoder.eval()
encoder = autoencoder.encoder
encoder = EncocderWrapper(encoder)

model = CustomTransformerModel(encoder, 2).to(device)

sampler = MNISTRandomSampler()

/var/folders/sv/xzgywwf17_d3f25rzb7z7jjh0000gn/T/ipykernel_95741/2531428739.py:2: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  autoencoder.load_state_dict(torch.load(autoen

In [12]:
for epoch in range(5):  # Run for 5 epochs as an example
    images, labels = sampler.sample(num_images=10, batch_size=4)
    images = images.to(device)
    labels = labels.to(device)
    result = model.forward(images, labels)
    print(labels)

tensor([[-0.3829,  0.1999],
        [-0.4834,  0.1436],
        [-0.4066,  0.2658],
        [-0.2915,  0.2750]], device='mps:0', grad_fn=<LinearBackward0>)
tensor([[-0.3942, -0.1146],
        [-0.3466, -0.2941],
        [-0.5369, -0.1288],
        [-0.3597, -0.1951]], device='mps:0', grad_fn=<LinearBackward0>)
tensor([[-0.4525, -0.4715],
        [-0.3663, -0.6323],
        [-0.2901, -0.6437],
        [-0.2242, -0.5107]], device='mps:0', grad_fn=<LinearBackward0>)
tensor([[-0.4717, -0.0543],
        [-0.3666, -0.2110],
        [-0.4955, -0.0093],
        [-0.3177, -0.2026]], device='mps:0', grad_fn=<LinearBackward0>)
tensor([[-0.7932, -0.4632],
        [-0.4938, -0.2500],
        [-0.5368, -0.4811],
        [-0.7022, -0.3954]], device='mps:0', grad_fn=<LinearBackward0>)
